---
- import_playbook: playbooks/preparePhysicalESXi.yml
- import_playbook: playbooks/deployVC.yml
- import_playbook: playbooks/prepareISOInstaller.yml
- import_playbook: playbooks/deployNestedESXi.yml

- name: Wait 5 minutes the ESXi hosts to become fully responsive
  hosts: localhost
  gather_facts: False
  vars_files:
    - ./answerfile.yml
  tasks:
    - name: Wait 5 minutes before checking whether the hosts are ready
      pause: minutes=5
      when: vESX|length > 5
- import_playbook: playbooks/configureNestedESXi.yml
- import_playbook: playbooks/createVDS.yml
- import_playbook: playbooks/moveESXiVMs.yml
- import_playbook: playbooks/deployNsxManager.yml
- import_playbook: playbooks/deployNsxEdge.yml
- import_playbook: playbooks/RegisterNsxComputeManager.yml
- import_playbook: playbooks/addNsxTz.yml
- import_playbook: playbooks/addNsxUplinkProfiles.yml


