##
##    Project: SDDC.Lab
##    Authors: Luis Chanu & Rutger Blom
##   Filename: requirements.yml
##
---
collections:
- community.general
- community.vmware
- community.crypto
- vyos.vyos
- ansible.posix
