---
- hosts: 127.0.0.1
  connection: local 
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Check if NSX-T license file exists
      stat: 
        path: "{{ nsxlicense }}"
      register: nsxlicensekey
    - name: Attach NSX-T transport node profile to vSphere cluster
      nsxt_transport_node_collections:
        hostname: "{{ nsxman.nsxman01.hostname }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        display_name: "TNC"
        resource_type: "TransportNodeCollection"
        description: "Transport Node Collections"
        compute_manager_name: "{{ vcenter.fqdn }}"
        cluster_name: "Compute"
        transport_node_profile_name: "esxi-tnp"
        state: present
      when: 
        - nsxlicensekey.stat.exists == True
        - deploy_nsxt == true
